---
title: "Fishers' access to fish and mental health"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


AS OF DECEMBER 20, 2021 THIS IS IN OBSIDIAN. MAYBE WE'LL MOVE IT BACK LATER IF WE WANT TO MAKE A DYNAMIC DOCUMENT.

### Introduction

What is the relationship between fishers’ access to fish and their mental wellbeing

Descriptive paper

Discussion of pathways, but maybe we don’t disentangle them fully

Directions for future research

Following King et al methodology



### Background


What do we know about fisher mental health in general?

* Disruption of fishery --> high levels of persisting mental distress (Scyphers et al 2019). Relevant covariates: trust, coccupational diversity, employment of family members, # of employees, # of dependents, income, gender, birth year, marital status.

What do we know about natural resource access and mental health?

What are potential resource-health (or mental health if enough lit) pathways that have been explored?

Context: What do we know about fisher health on Mfangano
Context: What drives fish access on Mfangano? 

Context: What do we know about fishing on Mfangano?



### Data and Methodology

Structure and purpose of survey

Outcome variable(s)—describe and summarize

Key predictor variable(s)—describe and summarize

Key covariates—describe and summarize

Data we can use to isolate potential pathways (e.g. income), if we can

Models used

Claims and shortcomings of modeling approach


### Results



### Conclusions

Directions for future research

Link to climate change and changing resource base, livelihoods

Mention governance regimes that impact resource access?

